### ISSUE TITLE
Error finding pools for node: node belongs to more than one MachineConfigPool

### ISSUE THREAD

**Issue by praveenkumar** [openshift/machine-config-operator#571] opened 2019-03-22 16:45 UTC
**Description**

machine-config-operator is in False state because master is labeled as master and worker which should be the case.

**Steps to reproduce the issue:**
1.  Use https://github.com/openshift/installer/blob/master/docs/user/customization.md#control-plane-with-no-taints to make master node no-taint one.
2. Edit the $CLUSTER_DIR/openshift/99_openshift-cluster-api_master-machines-0.yaml and add worker as label also
3. start the installer on libvirt provider using this manifest.

**Describe the results you received:**

```
$ oc get co | grep machine-config
machine-config                        4.0.0-0.alpha-2019-03-22-124110   False       True          True      18m
$ oc get co machine-config -oyaml
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  creationTimestamp: 2019-03-22T15:48:43Z
  generation: 1
  name: machine-config
  resourceVersion: "16803"
  selfLink: /apis/config.openshift.io/v1/clusteroperators/machine-config
  uid: f8c2b310-4cb9-11e9-bbb1-52fdfc072182
spec: {}
status:
  conditions:
  - lastTransitionTime: 2019-03-22T15:48:43Z
    message: Cluster not available for 4.0.0-0.alpha-2019-03-22-124110
    status: "False"
    type: Available
  - lastTransitionTime: 2019-03-22T15:48:43Z
    message: Cluster is bootstrapping 4.0.0-0.alpha-2019-03-22-124110
    status: "True"
    type: Progressing
  - lastTransitionTime: 2019-03-22T15:49:35Z
    message: 'Failed to resync 4.0.0-0.alpha-2019-03-22-124110 because: error pool
      master is not ready. status: (total: 1, updated: 0, unavailable: 0)'
    reason: 'error pool master is not ready. status: (total: 1, updated: 0, unavailable:
      0)'
    status: "True"
    type: Failing
  extension:
    master: 0 out of 1 nodes have updated to latest configuration rendered-master-020cc6964b5847dfc037fc2f53a192de
    worker: 0 out of 1 nodes have updated to latest configuration rendered-worker-60eee69a909e9f4604754d616f4dd3db
  relatedObjects:
  - group: ""
    name: openshift-machine-config-operator
    resource: namespaces
  versions:
  - name: operator
    version: 4.0.0-0.alpha-2019-03-22-124110
    
$ oc get csr
NAME        AGE   REQUESTOR                                                                   CONDITION
csr-8mb6l   24m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-n4q46   24m   system:node:test1-j2ltf-master-0                                            Approved,Issued

$ oc logs pod/machine-config-controller-7767bc8b9-qpnkx -n openshift-machine-config-operator
[...]
I0322 16:03:17.499026       1 node_controller.go:437] Setting node test1-j2ltf-master-0 to desired config rendered-master-020cc6964b5847dfc037fc2f53a192de
I0322 16:03:17.523483       1 status.go:159] Node test1-j2ltf-master-0 unavailable: different configs true or node not ready false
I0322 16:03:17.607509       1 status.go:159] Node test1-j2ltf-master-0 unavailable: different configs true or node not ready false
E0322 16:03:17.706096       1 node_controller.go:197] error finding pools for node: node test1-j2ltf-master-0 belongs to more than one MachineConfigPool, cannot proceed with this Node


$ oc get  nodes -o wide
NAME                   STATUS   ROLES           AGE   VERSION              INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                                                   KERNEL-VERSION         CONTAINER-RUNTIME
test1-j2ltf-master-0   Ready    master,worker   55m   v1.12.4+d14915559e   192.168.126.11   <none>        Red Hat Enterprise Linux CoreOS 410.8.20190320.1 (Ootpa)   4.18.0-80.el8.x86_64   cri-o://1.12.8-1.rhaos4.0
.git35a0cc1.el7

```

**Describe the results you expected:**
This should be working since a node can have multiple label.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `oc adm release info --commits | grep machine-config-operator`:**

```
$ oc adm release info --commits | grep machine-config-operator
  machine-config-controller                     https://github.com/openshift/machine-config-operator                       9da96326a5ff737869709f5fa2e6c716df4dbaf4
  machine-config-daemon                         https://github.com/openshift/machine-config-operator                       9da96326a5ff737869709f5fa2e6c716df4dbaf4
  machine-config-operator                       https://github.com/openshift/machine-config-operator                       9da96326a5ff737869709f5fa2e6c716df4dbaf4
  machine-config-server                         https://github.com/openshift/machine-config-operator                       9da96326a5ff737869709f5fa2e6c716df4dbaf4
  setup-etcd-environment                        https://github.com/openshift/machine-config-operator                       9da96326a5ff737869709f5fa2e6c716df4dbaf4
```

**Additional environment details (platform, options, etc.):**
libvirt provider.

Simillar issue #429

**Comment by kikisdeliveryservice** [comment] 2019-03-22 17:12
@praveenkumar machine configs currently do not support multiple roles.  From:
https://github.com/openshift/machine-config-operator
`Note this configuration only applies to workers (see the role: worker label); currently if you want to apply to both master and workers, you must create two separate MachineConfig objects.`

**Comment by runcom** [comment] 2019-03-23 00:05
I believe this is a duplicate of #429 - I'm not sure this scenario is supported though other than on libvirt. If it's supported, then surely it's a bug we need to fix

**Comment by praveenkumar** [comment] 2019-03-25 05:48
> for machine configs we currently do not support multiple roles.

@kikisdeliveryservice So as per the README doc it make sense if I need to apply a machine config on different label (like master and worker). As per my use case I just want to have my master also behave like worker and workloads are transferred to it once it is no tainted. During 0.14.0 installer release timeframe it was working and didn't see this kind of issue, is this recently changed?

cc @abhinavdahiya

**Comment by runcom** [comment] 2019-03-25 09:02
> During 0.14.0 installer release timeframe it was working and didn't see this kind of issue, is this recently changed?

This has never worked afaict. Master and worker roles are different enough to not be applicable to just a machine

**Comment by cgwalters** [comment] 2019-03-25 13:51
>for machine configs we currently do not support multiple roles.

This is the opposite problem in a sense - it's a machine with multiple roles, whereas the issue I think you're talking about is having a single MC apply to multiple roles (separate machines).

> I believe this is a duplicate of #429 

Yeah, although in this case we're talking about the MCO's built-in roles.  Hm.  In this case I believe we don't want *any* worker config to apply to the machine, the master config should be sufficient.  

> I'm not sure this scenario is supported though other than on libvirt.

We need to support CodeReady Containers for sure.

How about something like this?

```
diff --git a/pkg/controller/node/node_controller.go b/pkg/controller/node/node_controller.go
index b7d01b0..7c201da 100644
--- a/pkg/controller/node/node_controller.go
+++ b/pkg/controller/node/node_controller.go
@@ -254,6 +254,36 @@ func nodeChanged(old, cur *corev1.Node) bool {
        return false
 }
 
+// poolSubsumes returns true if primary takes over the role of secondary
+// This is currently needed to support at least CodeReady Containers which
+// has a "single master", no worker setup.
+// https://github.com/openshift/machine-config-operator/issues/571
+func poolSubsumes(primary, secondary *mcfgv1.MachineConfigPool) bool {
+       return primary.Name == "master" && secondary.Name == "worker"
+}
+
+// removeSubsumedPools filters out elements in pools which are subsumed by another pool
+func removeSubsumedPools(pools []*mcfgv1.MachineConfigPool) []*mcfgv1.MachineConfigPool {
+       var ret []*mcfgv1.MachineConfigPool
+       var subsumed map[string]bool
+       for i, primary := range pools {
+               for j, secondary := range pools {
+                       if i == j {
+                               continue
+                       }
+                       if poolSubsumes(primary, secondary) {
+                               subsumed[secondary.Name] = true
+                       }
+               }
+       }
+       for _, pool := range pools {
+               if !subsumed[pool.Name] {
+                       ret = append(ret, pool)
+               }
+       }
+       return ret
+}
+
 func (ctrl *Controller) getPoolForNode(node *corev1.Node) (*mcfgv1.MachineConfigPool, error) {
        pl, err := ctrl.mcpLister.List(labels.Everything())
        if err != nil {
@@ -279,6 +309,7 @@ func (ctrl *Controller) getPoolForNode(node *corev1.Node) (*mcfgv1.MachineConfig
                // This is not an error, as there might be nodes in cluster that are not managed by machineconfigpool.
                return nil, nil
        }
+       pools = removeSubsumedPools(pools)
        if len(pools) > 1 {
                return nil, fmt.Errorf("node %s belongs to more than one MachineConfigPool, cannot proceed with this Node", node.Name)
        }
```

**Comment by runcom** [comment] 2019-03-25 14:00
@cgwalters forgot about CodeReady Containers, thanks. And yeah, the above could work just fine.

**Comment by praveenkumar** [comment] 2019-03-25 14:59
> forgot about CodeReady Containers

@runcom Please don't forget about us :)

> How about something like this?

@cgwalters thanks for the patch, can this be the part of the controller?

**Comment by cgwalters** [comment] 2019-03-25 15:32
> @cgwalters thanks for the patch, can this be the part of the controller?

Yep, I'm on it.

**Closed** 2019-03-25 22:35 UTC
